from __future__ import annotations

from pathlib import Path

from .model import Structure


CHAIN_IDS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

RESIDUE_BONDS = (
    ("C1", "H1"), ("C1", "C2"), ("C1", "O5"),
    ("C2", "H2"), ("C2", "O2"), ("C2", "C3"), ("O2", "HO2"),
    ("C3", "H3"), ("C3", "O3"), ("C3", "C4"), ("O3", "HO3"),
    ("C4", "H4"), ("C4", "O4"), ("C4", "C5"),
    ("C5", "H5"), ("C5", "O5"), ("C5", "C6"),
    ("C6", "H61"), ("C6", "H62"), ("C6", "O6"), ("O6", "HO6"),
)


def _atom_field(name: str) -> str:
    return f" {name:<3}" if len(name) < 4 else name[:4]


def write_pdb(path: str | Path, structure: Structure, conect: bool = True) -> None:
    if len(structure.chains) > len(CHAIN_IDS):
        raise ValueError("PDB supports at most 62 distinct one-character chain IDs")
    lines = [
        "REMARK  Generated by dynamics_cellulose",
        f"REMARK  Allomorph: cellulose {structure.allomorph}",
        "REMARK  Experimental coordinates: COD 4114994",
        "REMARK  Nishiyama Y, Langan P, Chanzy H; JACS 2002, 124, 9074-9082",
        "REMARK  DOI: 10.1021/ja0257319",
        "REMARK  Symmetry expansion and finite-chain construction by dynamics_cellulose",
        "REMARK  Heavy atoms and C-H coordinates derive from COD 4114994",
        "REMARK  Missing hydroxyl H atoms were modeled with tetrahedral O-H geometry",
        f"REMARK  Glucose units per chain: {structure.glucose_units}",
        f"REMARK  Layers top-to-bottom: {','.join(map(str, structure.layers))}",
        f"REMARK  Chains: {len(structure.chains)}",
    ]
    serial = 1
    serials: dict[tuple[int, int, str], int] = {}
    bonds: set[tuple[int, int]] = set()
    for chain in structure.chains:
        chain_id = CHAIN_IDS[chain.number - 1]
        segment = f"C{chain.number:03d}"
        for residue in chain.residues:
            for atom in residue.atoms:
                if serial > 99999:
                    raise ValueError(
                        "structure exceeds the 99,999-atom limit of classic PDB; "
                        "use fewer chains/units or add an mmCIF writer"
                    )
                x, y, z = atom.position
                if max(abs(x), abs(y), abs(z)) >= 10000:
                    raise ValueError("coordinate exceeds the classic PDB field limit")
                serials[(chain.number, residue.number, atom.name)] = serial
                lines.append(
                    f"ATOM  {serial:5d} {_atom_field(atom.name)} BGLC{chain_id}"
                    f"{residue.number:4d}    {x:8.3f}{y:8.3f}{z:8.3f}"
                    f"{1.0:6.2f}{0.0:6.2f}      {segment:<4}{atom.element:>2}"
                )
                serial += 1

        lines.append(f"TER   {serial:5d}      BGLC{chain_id}{chain.residues[-1].number:4d}")
        serial += 1

        for residue in chain.residues:
            names = {atom.name for atom in residue.atoms}
            for first, second in RESIDUE_BONDS:
                if first in names and second in names:
                    a = serials[(chain.number, residue.number, first)]
                    b = serials[(chain.number, residue.number, second)]
                    bonds.add(tuple(sorted((a, b))))
            for first, second in (("O4", "HO4"), ("C1", "O1"), ("O1", "HO1")):
                if first in names and second in names:
                    a = serials[(chain.number, residue.number, first)]
                    b = serials[(chain.number, residue.number, second)]
                    bonds.add(tuple(sorted((a, b))))
        for resid in range(1, structure.glucose_units):
            a = serials[(chain.number, resid, "C1")]
            b = serials[(chain.number, resid + 1, "O4")]
            bonds.add(tuple(sorted((a, b))))

    if conect:
        adjacency: dict[int, list[int]] = {}
        for first, second in sorted(bonds):
            adjacency.setdefault(first, []).append(second)
            adjacency.setdefault(second, []).append(first)
        for atom_serial in sorted(adjacency):
            neighbors = adjacency[atom_serial]
            for start in range(0, len(neighbors), 4):
                lines.append(
                    f"CONECT{atom_serial:5d}" + "".join(f"{n:5d}" for n in neighbors[start : start + 4])
                )
    lines.append("END")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
