from __future__ import annotations

from pathlib import Path

from .model import Structure


CHAIN_IDS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
# HO62 is intentionally retained: unlike alcohol hydroxyl hydrogens, it
# explicitly distinguishes a requested neutral COOH from COO- chemistry.
HYDROXYL_HYDROGENS = frozenset({"HO1", "HO2", "HO3", "HO4", "HO6"})

RESIDUE_BONDS = (
    ("C1", "H1"), ("C1", "C2"), ("C1", "O5"),
    ("C2", "H2"), ("C2", "O2"), ("C2", "C3"), ("O2", "HO2"),
    ("C3", "H3"), ("C3", "O3"), ("C3", "C4"), ("O3", "HO3"),
    ("C4", "H4"), ("C4", "O4"), ("C4", "C5"),
    ("C5", "H5"), ("C5", "O5"), ("C5", "C6"),
    ("C6", "H61"), ("C6", "H62"), ("C6", "O6"), ("O6", "HO6"),
)


def _atom_field(name: str) -> str:
    return f" {name:<3}" if len(name) < 4 else name[:4]


def write_pdb(
    path: str | Path,
    structure: Structure,
    conect: bool = True,
    charmm_gui: bool = False,
) -> None:
    """Write a conventional or CHARMM-GUI-ready PDB.

    The CHARMM-GUI profile omits hydroxyl hydrogen coordinates and writes each
    chain in the O4(i)-C1(i+1) direction expected by the carbohydrate reader.
    Heavy atoms and carbon-bound hydrogens are never removed.
    """
    if len(structure.chains) > len(CHAIN_IDS):
        raise ValueError("PDB supports at most 62 distinct one-character chain IDs")
    lines = [
        "REMARK  Generated by dynamics_cellulose (cellulose_core)",
        f"REMARK  Allomorph: cellulose {structure.allomorph}",
        "REMARK  Experimental coordinates: COD 4114994",
        "REMARK  Nishiyama Y, Langan P, Chanzy H; JACS 2002, 124, 9074-9082",
        "REMARK  DOI: 10.1021/ja0257319",
        "REMARK  Symmetry expansion and finite-chain construction by cellulose_core",
        "REMARK  Heavy atoms and C-H coordinates derive from COD 4114994",
        "REMARK  Missing hydroxyl H atoms were modeled with tetrahedral O-H geometry",
        f"REMARK  Glucose units per chain: {structure.glucose_units}",
        f"REMARK  Layers top-to-bottom: {','.join(map(str, structure.layers))}",
        f"REMARK  Chains: {len(structure.chains)}",
    ]
    if charmm_gui:
        lines.extend((
            "REMARK  CHARMM-GUI input profile enabled",
            "REMARK  Hydroxyl H coordinates omitted for topology-based placement",
            "REMARK  Residue blocks ordered for O4(i)-C1(i+1) recognition",
        ))
    oxidized_count = sum(
        residue.oxidized for chain in structure.chains for residue in chain.residues
    )
    if structure.oxidation_scope is not None:
        state = "protonated COOH" if structure.oxidation_protonated else "deprotonated COO-"
        lines.extend((
            "REMARK  C6 oxidation enabled",
            f"REMARK  Oxidation eligibility model: {structure.oxidation_model}",
            f"REMARK  Oxidation scope: {structure.oxidation_scope}",
            f"REMARK  Requested oxidation degree: {structure.oxidation_degree:.6f}",
            f"REMARK  Eligible C6 sites: {structure.oxidation_eligible_sites}",
            f"REMARK  Oxidized C6 sites: {oxidized_count}",
            f"REMARK  Oxidation state: {state}",
            f"REMARK  Random seed: {structure.oxidation_seed}",
        ))
    serial = 1
    serials: dict[tuple[int, int, str], int] = {}
    bonds: set[tuple[int, int]] = set()
    for chain in structure.chains:
        chain_id = CHAIN_IDS[chain.number - 1]
        segment = f"C{chain.number:03d}"
        output_residues = list(reversed(chain.residues)) if charmm_gui else chain.residues
        for output_number, residue in enumerate(output_residues, start=1):
            atoms = (
                atom for atom in residue.atoms
                if not charmm_gui or atom.name not in HYDROXYL_HYDROGENS
            )
            for atom in atoms:
                if serial > 99999:
                    raise ValueError(
                        "structure exceeds the 99,999-atom limit of classic PDB; "
                        "use fewer chains/units or add an mmCIF writer"
                    )
                x, y, z = atom.position
                if max(abs(x), abs(y), abs(z)) >= 10000:
                    raise ValueError("coordinate exceeds the classic PDB field limit")
                serials[(chain.number, output_number, atom.name)] = serial
                lines.append(
                    f"ATOM  {serial:5d} {_atom_field(atom.name)} BGLC{chain_id}"
                    f"{output_number:4d}    {x:8.3f}{y:8.3f}{z:8.3f}"
                    f"{1.0:6.2f}{0.0:6.2f}      {segment:<4}{atom.element:>2}"
                )
                serial += 1

        lines.append(f"TER   {serial:5d}      BGLC{chain_id}{chain.residues[-1].number:4d}")
        serial += 1

        for output_number, residue in enumerate(output_residues, start=1):
            names = {
                atom.name for atom in residue.atoms
                if not charmm_gui or atom.name not in HYDROXYL_HYDROGENS
            }
            for first, second in RESIDUE_BONDS:
                if first in names and second in names:
                    a = serials[(chain.number, output_number, first)]
                    b = serials[(chain.number, output_number, second)]
                    bonds.add(tuple(sorted((a, b))))
            for first, second in (("O4", "HO4"), ("C1", "O1"), ("O1", "HO1")):
                if first in names and second in names:
                    a = serials[(chain.number, output_number, first)]
                    b = serials[(chain.number, output_number, second)]
                    bonds.add(tuple(sorted((a, b))))
            for first, second in (("C6", "O61"), ("C6", "O62"), ("O62", "HO62")):
                if first in names and second in names:
                    a = serials[(chain.number, output_number, first)]
                    b = serials[(chain.number, output_number, second)]
                    bonds.add(tuple(sorted((a, b))))
        for resid in range(1, structure.glucose_units):
            if charmm_gui:
                a = serials[(chain.number, resid, "O4")]
                b = serials[(chain.number, resid + 1, "C1")]
            else:
                a = serials[(chain.number, resid, "C1")]
                b = serials[(chain.number, resid + 1, "O4")]
            bonds.add(tuple(sorted((a, b))))

    if conect:
        adjacency: dict[int, list[int]] = {}
        for first, second in sorted(bonds):
            adjacency.setdefault(first, []).append(second)
            adjacency.setdefault(second, []).append(first)
        for atom_serial in sorted(adjacency):
            neighbors = adjacency[atom_serial]
            for start in range(0, len(neighbors), 4):
                lines.append(
                    f"CONECT{atom_serial:5d}" + "".join(f"{n:5d}" for n in neighbors[start : start + 4])
                )
    lines.append("END")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
